language: node_js
node_js:
  - 0.10
rvm:
  - "1.8.7"
notifications:
  email:
    on_success: never
    on_failure: change
before_install: npm install -g grunt-cli && gem install sass && gem install compass

